### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by rohanpsingh** [rohanpsingh/mc_mujoco#19]
After "[error] QP failed to run()" has happened, reset function does not work as expected.  
If we pause (using "step-by-step" button) and resume, the robot will fly away! The reset will begin to work normally after this.  

I didn't look into this at all... yet.

The video is using HRP-5P with CoM controller.  

https://drive.google.com/file/d/1KlcByJSWUURXo8I7rive_7rQkQxjr4j-/view?usp=sharing

**Comment by gergondet** [comment]
Hi @rohanpsingh 

Thanks for reporting this. I believe it is fixed by the above commit.

**Comment by rohanpsingh** [comment]
Wow, thanks a lot! Sorry I didn't find the time to investigate it further.
