### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by tabinohito** [rohanpsingh/mc_mujoco#42]
Hi,I tried to install mc_mujoco.
I read ReadMe and download mujoco2.1.2 but  I faced error when I do "make" this program.
So, I change the mujoco2.3.5 version and it success.

Which version of mujoco is currently supported by mc_mujoco?

**Comment by rohanpsingh** [comment]
All mujoco versions upto mujoco2.3.5 should be supported as of now. 
You can pull the latest changes of `mc_mujoco` and retry. Or, post the error that you are facing here :)

**Comment by rohanpsingh** [comment]
More specifically, if you don't have the commit https://github.com/rohanpsingh/mc_mujoco/commit/589dfc5ff31290dbc2077b00020d4bae76a4fdaf, your build could fail for mujoco < 2.3.5.
