### ISSUE TITLE
error: invalid conversion from ‘int’ to ‘ImGuiKey’ [-fpermissive]

### ISSUE THREAD

**Issue by robotlinker** [rohanpsingh/mc_mujoco#46]
Hi I have a make problem while git pull the latest version:
![Screenshot from 2023-06-01 14-56-18](https://github.com/rohanpsingh/mc_mujoco/assets/24693929/1a9dfa09-98e9-4b83-92a9-6b2b046e4494)

**Comment by rohanpsingh** [comment]
Hi, it seems you don't have the latest changes in `mc_rtc-imgui`, did you do git pull `recursively`?
Please do `$ git pull --recurse-submodules` and retry `make`.

**Comment by robotlinker** [comment]
It work very well, thank you!
